package gesrdvv;

import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
public class gesmedecin extends javax.swing.JFrame {
    private static String url = "jdbc:mysql://localhost:3306/gesrdv";    
    private static String driverName = "com.mysql.cj.jdbc.Driver";   
    private static String username = "root";   
    private static String password = "";
    private static Connection con;
    private static String urlstring;
    long medecinid[];
    
    ButtonGroup b = new ButtonGroup();
    public gesmedecin() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage((new ImageIcon(getClass().getResource("/images/hospital.png")).getImage()));
        medecinid = new long[100];
        int index = 0;
        try{
          Class.forName(driverName);
          Connection con = null;
          con = DriverManager.getConnection(url,username,password);
          Statement s = con.createStatement();
          String sql = "SELECT * FROM medecin";
          ResultSet res = s.executeQuery(sql);
          while(res.next()){

              jComboBox1.addItem(res.getString("idmedecin"));
          }
        }
        catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null,"err de pilote"); 
        }
        catch(SQLException s){
            JOptionPane.showMessageDialog(null,"err de connexion"); 
        }
        
        try{
          Class.forName(driverName);
          Connection con = null;
          con = DriverManager.getConnection(url,username,password);
          Statement s = con.createStatement();
          String sql = "SELECT idspecialite,lib FROM specialite";
          ResultSet res = s.executeQuery(sql);
          while(res.next()){
              medecinid[index] = res.getLong(1);
              index++;
              jComboBox2.addItem(res.getString("lib"));
          }
        }
        catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null,"err de pilote"); 
        }
        catch(SQLException s){
            JOptionPane.showMessageDialog(null,"err de connexion"); 
        }
        jRadioButton1.setActionCommand("Homme");
        jRadioButton2.setActionCommand("Femme");
        b.add(jRadioButton1);b.add(jRadioButton2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Des Médecins");
        setResizable(false);

        jRadioButton2.setText("Femme");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choisir..." }));

        jLabel2.setText("ID");

        jLabel3.setText("Genre");

        jLabel12.setText("Specialite");

        jLabel4.setText("Nom");

        jLabel5.setText("Prenom");

        jLabel6.setText("Date Embauche");

        jLabel7.setText("Date Naissance");

        jLabel8.setText("Addresse");

        jLabel9.setText("Téléphone");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loupe.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-user.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remove-user.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("Homme");

        jLabel1.setFont(new java.awt.Font("Arial Nova Cond", 0, 24)); // NOI18N
        jLabel1.setText("GESTION DES MEDECINS");

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField2)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2))
                            .addComponent(jComboBox1, 0, 148, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jComboBox1.setSelectedItem("choisir...");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        Calendar clndr = null;
        jDateChooser1.setDate(null);
        jDateChooser2.setDate(null);
        b.clearSelection();
       
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try{
            Class.forName(driverName);
            Connection con = null;
            con = DriverManager.getConnection(url,username,password);
            Statement s = con.createStatement();
            String sql = "SELECT * FROM medecin WHERE idmedecin = "+jComboBox1.getSelectedItem()+" ";
            ResultSet res = s.executeQuery(sql);
            while(res.next()){
                if(res.getInt("idspecialite") == 1){
                    jComboBox2.setSelectedItem("cardiologie");
                }
                else if(res.getInt("idspecialite") == 2){
                    jComboBox2.setSelectedItem("chirurgie");
                }
                else if(res.getInt("idspecialite") == 3){
                    jComboBox2.setSelectedItem("Dermatologie");
                }
                else if(res.getInt("idspecialite") == 4){
                    jComboBox2.setSelectedItem("Gériatrie");
                }
                else if(res.getInt("idspecialite") == 5){
                    jComboBox2.setSelectedItem("Oncologie");
                }
                else if(res.getInt("idspecialite") == 6){
                    jComboBox2.setSelectedItem("Pediatrie");
                }
                else if(res.getInt("idspecialite") == 7){
                    jComboBox2.setSelectedItem("Allergologie");
                }
                jTextField2.setText(res.getString("nom"));
                jTextField3.setText(res.getString("prenom"));
                jDateChooser1.setDate(res.getDate("date_embauche"));
                jDateChooser2.setDate(res.getDate("date_naissance"));
                jTextField5.setText(res.getString("addresse"));
                jTextField6.setText(res.getString("telephone"));
                if("Femme".equals(res.getString("genre"))){
                    jRadioButton2.setSelected(true);
                }
                else{
                    jRadioButton1.setSelected(true);
                }

            }
        }
        catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null,"err de pilote");
        }
        catch(SQLException s){
            JOptionPane.showMessageDialog(null,"err de connexion");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          
            SimpleDateFormat ss = new SimpleDateFormat("yyyy-MM-dd");
            String date2 = ss.format(jDateChooser2.getDate());
              Date myD = new java.util.Date(); 
            if(jDateChooser2.getDate().after(myD)){
                JOptionPane.showMessageDialog(null,"Erreu de date d'embauche");
            } 
            else if(myD.getYear() - jDateChooser1.getDate().getYear() <= 25){
                JOptionPane.showMessageDialog(null,"Erreur de date naissance");
            }
            else{
                if(jTextField2.getText().length() <= 0 || jTextField3.getText().length() <= 0 || jTextField5.getText().length() <= 0 || jTextField6.getText().length() <= 0 || b.getSelection()== null){
                    JOptionPane.showMessageDialog(null,"Vous n'avais pas saisis un champ obligatoire");
                }
                else{
                           try {
            Class.forName(driverName);
            con = DriverManager.getConnection(url, username, password);
            Statement stmt = con.createStatement();
            
            String date = ss.format(jDateChooser1.getDate());
            
            String sql = "INSERT INTO medecin(idspecialite,genre,nom,prenom,date_embauche,date_naissance,addresse,telephone)"
                    + "VALUES("+medecinid[jComboBox2.getSelectedIndex()]+",'"+b.getSelection().getActionCommand()+"','"+jTextField2.getText()+"','"+jTextField3.getText()+"','"+date+"','"+date2+"','"+jTextField5.getText()+"','"+jTextField6.getText()+"')";
            int res = stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Les informations sont inseres");

        } catch (ClassNotFoundException ex) {
            // log an exception. for example:
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
        catch(SQLException s){
            JOptionPane.showMessageDialog(null,s.getMessage());
        }
             
                                jComboBox1.removeAllItems();        
        jComboBox1.setSelectedItem("choisir...");
        jComboBox2.setSelectedItem("cardiologie");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jDateChooser1.setDate(null);
        jDateChooser2.setDate(null);
        b.clearSelection();
            }

        jComboBox1.removeAllItems();
        try{
            Class.forName(driverName);
            Connection con = null;
            con = DriverManager.getConnection(url,username,password);
            Statement s = con.createStatement();
            String sql = "SELECT * FROM medecin";
            ResultSet res = s.executeQuery(sql);
            jComboBox1.addItem("choisir...");
            while(res.next()){
                jComboBox1.addItem(res.getString("idmedecin"));
            }
        }
        catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null,"err de pilote");
        }
        catch(SQLException s){
            JOptionPane.showMessageDialog(null,"err de connexion");
        }
                }
                 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
             Date myD = new java.util.Date(); 
            if(jDateChooser2.getDate().after(myD)){
                JOptionPane.showMessageDialog(null,"Erreu de date d'embauche");
            } 
            else if(myD.getYear() - jDateChooser1.getDate().getYear() <= 25){
                JOptionPane.showMessageDialog(null,"Erreur de date naissance");
            }
            else{
                if(jTextField2.getText().length() <= 0 || jTextField3.getText().length() <= 0 || jTextField5.getText().length() <= 0 || jTextField6.getText().length() <= 0 || b.getSelection()== null){
                    JOptionPane.showMessageDialog(null,"Vous n'avais pas saisis un champ obligatoire");
                }
                else{
                   try {           
                        Class.forName(driverName);
                        con = DriverManager.getConnection(url, username, password);
                        Statement stmt = con.createStatement();
                        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
                        String date = s.format(jDateChooser1.getDate());
                        String date2 = s.format(jDateChooser2.getDate());
                        String sql = "UPDATE medecin SET idspecialite = "+medecinid[jComboBox2.getSelectedIndex()]+",genre = '"+b.getSelection().getActionCommand()+"',nom = '"+jTextField2.getText()+"',prenom = '"+jTextField3.getText()+"',date_embauche = '"+date+"',date_naissance = '"+date2+"',addresse = '"+jTextField5.getText()+"',telephone = '"+jTextField6.getText()+"' WHERE idmedecin = "+jComboBox1.getSelectedItem()+" ";
                        int a = JOptionPane.showConfirmDialog(null, "Voulez vraiment modifier les informations de ce medecin?");
                        if(a == 0){
                            int res = stmt.executeUpdate(sql);}

                    } catch (ClassNotFoundException ex) {
                        // log an exception. for example:
                        JOptionPane.showMessageDialog(null,ex.getMessage());
                    }
                    catch(SQLException s){
                        JOptionPane.showMessageDialog(null,s.getMessage());
                    }  
                }
        
            }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            Class.forName(driverName);
            con = DriverManager.getConnection(url, username, password);
            Statement stmt = con.createStatement();
            String sql = "DELETE FROM medecin WHERE idmedecin = "+jComboBox1.getSelectedItem()+"";
            int a = JOptionPane.showConfirmDialog(null, "Voulez vraiment supprimer ce medecin?");
            if(a == 0){
                int res = stmt.executeUpdate(sql);}

        } catch (ClassNotFoundException ex) {
            // log an exception. for example:
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
        catch(SQLException s){
            JOptionPane.showMessageDialog(null,s.getMessage());
        }
        
        jComboBox1.removeAllItems();        
        jComboBox1.setSelectedItem("choisir...");
        jComboBox2.setSelectedItem("cardiologie");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        Calendar clndr = null;
        jDateChooser1.setDate(null);
        jDateChooser2.setDate(null);
        b.clearSelection();
        
        try{
            Class.forName(driverName);
            Connection con = null;
            con = DriverManager.getConnection(url,username,password);
            Statement s = con.createStatement();
            String sql = "SELECT * FROM medecin";
            ResultSet res = s.executeQuery(sql);
            jComboBox1.addItem("choisir...");
            while(res.next()){
                jComboBox1.addItem(res.getString("idmedecin"));
            }
        }
        catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null,"err de pilote");
        }
        catch(SQLException s){
            JOptionPane.showMessageDialog(null,"err de connexion");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.setVisible(false);
        new dashboard().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
